Hw04 lru cache
Nemizar/otus_home_work pull request #4
Opened 2023-07-16 17:54 UTC by Nemizar

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-07-16 18:05 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +func (c *lruCache) Clear() {
Метод Clear должен очищать весь кэш, а он удаляет только последний

2023-07-16 18:13 UTC, Nemizar commented on hw04_lru_cache/cache.go
> +func (c *lruCache) Clear() {
исправил

2023-07-16 18:14 UTC, vladislavmass requested changes
Хорошее начало. Потокобезопасность сделана хорошо. Работу пока принять немогу так как к ней есть ряд замечаний

2023-07-16 18:14 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.len == 0 {
Зачем занулять пустой список? Это ведь лишние такты работы процессора

2023-07-16 18:14 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.len == 1 {
В данном коде не происходит удаления. Как раз таки тут должно происходит зануление first и last

2023-07-16 18:14 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if i.Prev == nil {
Подумайте к чему при таком коде приведет если я после этого кода обращусь в `l.first.prev`

2023-07-16 18:14 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if i.Next == nil {
Подумайте к чему при таком коде приведет если я после этого кода обращусь в `l.last.next`

2023-07-18 04:59 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		l.first.Next = nil
В эту строчка закралась явная описка.

2023-07-18 05:06 UTC, vladislavmass requested changes
Код стал еще лучше, но нужны еще правки

2023-07-18 05:06 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	i.Prev.Next = i.Next
Нужно добавить также что-то вида `i.Next.Prev = i.Prev`

2023-07-18 05:06 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	i.Prev.Next = i.Next
А разве у некста не надо обновить prev

2023-07-19 07:07 UTC, HangryHoneyBadger approved these changes
Отлично. Работа принята. 10/10

2023-07-19 07:07 UTC, vladislavmass approved these changes
Отлично. Работа принята. 10/10

2023-07-19 07:08 UTC, merged